name: Trigger Sync to Mono Repo

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install jsonwebtoken axios
      - name: Dispatch sync event
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
        run: |
          node -e 'const jwt = require("jsonwebtoken");
          const axios = require("axios");
          const now = Math.floor(Date.now()/1000);
          const payload = { iat: now-60, exp: now+600, iss: process.env.APP_ID };
          const token = jwt.sign(payload, process.env.APP_PRIVATE_KEY, { algorithm: "RS256" });
          axios.post(`https://api.github.com/app/installations/${process.env.APP_INSTALLATION_ID}/access_tokens`, {}, {
            headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github.v3+json" }
          }).then(res => {
            const instToken = res.data.token;
            return axios.post(
              `https://api.github.com/repos/${process.env.ORG_NAME}/mono-repo/dispatches`,
              { event_type: "sync-code", client_payload: { repo_name: "app-repo" } },
              { headers: { Authorization: `token ${instToken}`, Accept: "application/vnd.github.v3+json" } }
            );
          }).then(() => {
            console.log("Sync event dispatched.");
          }).catch(err => {
            console.error("Error dispatching event:", err.response ? err.response.data : err);
            process.exit(1);
          });'
